---
# vars file for mq-testing
MQM_BIN_PATH: "/opt/mqm/bin"
queuemgrs: 
  - name: "HAQM1"
    queue: "HAQM1.LOCAL.QUEUE"
    channel: "HAQM1.SRVCONN"
    listener: "HAQM1.LISTENER"
    is_dr: false
    is_ha: true
    size: "1024M"
    listen_port: "1501"
  - name: "HAQM2"
    queue: "HAQM2.LOCAL.QUEUE"
    channel: "HAQM2.SRVCONN"
    listener: "HAQM2.LISTENER"
    is_dr: false
    is_ha: true
    size: "1024M"
    listen_port: "1502"
  - name: "HAQM3"
    queue: "HAQM3.LOCAL.QUEUE"
    channel: "HAQM3.SRVCONN"
    listener: "HAQM3.LISTENER"
    is_dr: false
    is_ha: true
    size: "2048M"
    listen_port: "1503"
enable_rdqm: true
create_queues: false

mqm_uid: 1001
mqm_gid: 1001

version: 9.3.2
os: rhel 
rel: el8

mq_storage_dev: vdb
rdqm_storage_dev: vdc

# Some env vars here

MQ_INSTALLATION_PATH: /opt/mqm
