- name: Download MQ Advanced for Developers
  get_url:
    url: "{{ mq_dl_url }}/mqadv_dev{{ version | replace('.', '') }}_{{ os }}_x86-64.tar.gz"
    dest: /tmp/mq.tar.gz
    force: no
  tags: download

- name: Extract MQ fom TAR
  unarchive:
    src: /tmp/mq.tar.gz
    remote_src: yes
    dest: /tmp
  tags: download