- name: Accept MQ License
  shell: "cd /tmp/MQServer/ && ./mqlicense.sh -accept"
  register: license_out 

- name: Collect a list of packages to install
  shell: "ls /tmp/MQServer/MQSeries*"
  register: packagelist

- debug:
    var: packagelist.stdout_lines

- name: Install MQ Software RPMS
  ansible.builtin.dnf:
    name: "{{ packagelist.stdout_lines }}" 
    disable_gpg_check: true
    state: present
  when: os == 'linux'