name: New Issue
description: Use this template to report any issue
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Bug
        - Build/Install
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
